<script setup>
import {Head, Link} from "@inertiajs/vue3";
import AppLayout from "@/Layouts/AppLayout.vue";
</script>

<template>
    <AppLayout>
        <Head>
            <title>Privacy Policy</title>

            <!-- Primary Meta Tags -->
            <meta name="title" content="Privacy Policy">
            <meta name="description"
                  content="Read about our commitment to your privacy. This policy clarifies data collection practices on levintoo.com for a transparent experience.">

            <!-- Open Graph / Facebook -->
            <meta property="og:type" content="website">
            <meta property="og:url" content="https://levintoo.com/privacy-policy">
            <meta property="og:title" content="Privacy Policy">
            <meta property="og:description"
                  content="Read about our commitment to your privacy. This policy clarifies data collection practices on levintoo.com for a transparent experience.">
            <meta property="og:image" content="https://levintoo.com/assets/og-image.png">
            <!-- Twitter -->
            <meta property="twitter:url" content="https://levintoo.com/privacy-policy">
            <meta property="twitter:card" content="summary_large_image">
            <meta property="twitter:title" content="Privacy Policy">
            <meta property="twitter:description"
                  content="Read about our commitment to your privacy. This policy clarifies data collection practices on levintoo.com for a transparent experience.">
            <meta property="twitter:image" content="https://levintoo.com/assets/og-image.png">
        </Head>

        <template #breadcrumbs>
            <span>privacy policy</span>
        </template>

        <div class="max-w-7xl mx-auto">
                    <div class="px-2 lg:px-0 mx-auto prose text-lg leading-loose">

                        <section class="space-y-8 font-light text-[20px]">
                            <h1>Privacy Policy</h1>
                            <p>Last updated: March 24, 2024</p>
                            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                            <h2>Interpretation and Definitions</h2>
                            <h3>Interpretation</h3>
                            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                            <h3>Definitions</h3>
                            <p>For the purposes of this Privacy Policy:</p>
                            <ul>
                                <li>
                                    <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
                                </li>
                                <li>
                                    <p><strong>Us</strong> (referred to as either &quot;Me&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to levintoo.com.</p>
                                </li>
                                <li>
                                    <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                                </li>
                                <li>
                                    <p><strong>Country</strong> refers to:  Kenya</p>
                                </li>
                                <li>
                                    <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
                                </li>
                                <li>
                                    <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
                                </li>
                                <li>
                                    <p><strong>Service</strong> refers to the Website.</p>
                                </li>
                                <li>
                                    <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                                </li>
                                <li>
                                    <p><strong>Website</strong> refers to levintoo.com, accessible from <Link href="https://levintoo.com" rel="external nofollow noopener">https://levintoo.com</Link></p>
                                </li>
                                <li>
                                    <p><strong>You</strong> means the individual accessing or using the Service, or We, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                                </li>
                            </ul>
                            <h2>Collecting and Using Your Personal Data</h2>
                            <h3>Types of Data Collected</h3>
                           <ul>
                                <li>Usage Data</li>
                            </ul>
                            <h4>Usage Data</h4>
                            <p>Usage Data is collected automatically when using the Service.</p>
                            <p>Usage Data may include information such as Your Device's browser type and the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                            <h4>Tracking Technologies and Cookies</h4>
                            <p>We use Cookies to store certain information.</p>
                            <ul>
                                <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                            </ul>
                            <p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
                            <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
                            <ul>
                                <li>
                                    <p><strong>Functionality Cookies</strong></p>
                                    <p>Type: Persistent Cookies</p>
                                    <p>Administered by: Us</p>
                                    <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
                                </li>
                            </ul>
                            <h3>Use of Your Personal Data</h3>
                            <p>We may use Personal Data for the following purposes:</p>
                            <ul>
                                <li>
                                    <p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>
                                </li>
                            </ul>
                            <h3>Delete Your Personal Data</h3>
                            <p>You have the right to delete by requesting that We assist in deleting the Personal Data that We have collected about You.</p>
                            <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
                            <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
                            <h3>Security of Your Personal Data</h3>
                            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                            <h2>Links to Other Websites</h2>
                            <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
                            <h2>Changes to this Privacy Policy</h2>
                            <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                            <h2>Contact</h2>
                            <p>If you have any questions about this Privacy Policy, You can contact levintoo:</p>
                            <ul>
                                <li>By visiting this page on my website: <a href="https://levintoo.com/about#contact" rel="external nofollow noopener">contact</a></li>
                            </ul>
                        </section>

                    </div>
                </div>
    </AppLayout>
</template>
